export default {
  reportsPath: "/reports",
  bankAccountsPath: "/bank_accounts",
  creditCardsPath: "/credit_cards",
  entriesPath: "/entries",
  customersPath: "/customers",
  vendorsPath: "/vendors",
  accountsPath: "/accounts",
  accountFundsPath: "/account_funds",
  accountResourcesPath: "/account_resources",
  accountYearsPath: "/account_years",
  accountGoalsPath: "/account_goals",
  accountFunctionsPath: "/account_functions",
  accountObjectsPath: "/account_objects",
  accountLocationsPath: "/account_locations",
  adminPath: "/admin",
  adminOrganizationPath: "/organizations",
  adminUsersPath: "/admin/users",
  adminImportPath: "/batch_uploads/new",
  importEntries: "/admin/import-entries",
};
