query addressSearch(
  $value: ID
  $addressableType: String
  $addressableIds: [ID]
) {
  addressSearch(
    addressable_type: $addressableType
    addressable_ids: $addressableIds
  ) {
    id
    addressableId
    addressableType
    line1
    line2
    city
    state
    zip
  }
  address(id: $value) {
    id
    name
    addressableId
    addressableType
    line1
    line2
    city
    state
    zip
  }
}
