query purchaseOrder($vendorSlug: String!, $slug: String!) {
  purchaseOrder: purchaseOrderBySlug(vendorSlug: $vendorSlug, slug: $slug) {
    id
    vendorId
    number
    dateNeeded

    errors
    errorMessages

    authorizations {
      id
      groupId
      groupName
      userName
      action
      reason
      date: updatedAt
    }

    authorizationPath {
      name
      id
    }
    authorizationPathIndex

    buyer
    requisitionNumber
    referenceNumber
    requestedById
    requestedForId

    requestedBy {
      fullName
      id
    }

    requestedFor {
      fullName
      id
    }

    slug
    fileUrl
    aasmState
    addressId
    vendorAddressId
    quoteDate
    quoteNumber
    proposalDate
    proposalNumber

    vendorName
    vendorPath
    invoiceId
    invoicePath
    createdAt
    updatedAt
    path
    editPath
    exportPath
    taxAmountInCents
    subtotalInCents
    shippingAmountInCents
    totalInCents

    permissions {
      index
      create
      edit
      view
      update
      delete
      save_draft
      send_for_approval
      reverse_approval
      approve
      deny
      authorize
    }

    stateChangeLogs {
      loggableType
      fromState
      toState
      createdAt
      user {
        fullName
      }
    }

    purchaseOrderItems {
      id
      purchaseOrderId
      order
      quantity
      description
      priceInCents
      totalInCents
    }

    address {
      id
      name
      line1
      line2
      city
      state
      zip
    }

    vendorAddress {
      id
      name
      line1
      line2
      city
      state
      zip
    }
  }

  permissions {
    index
    create
    edit
    view
    update
    delete
    save_draft
    send_for_approval
    reverse_approval
    approve
    deny
  }

  filestack {
    clientName
    security {
      signature
      policy
    }
  }

  vendor: vendorBySlug(slug: $vendorSlug) {
    vendorId: id
    slug
    organizationId
  }
}
