query {
  report: balanceSheetByMonth {
    accountFundCode
    accountFundName
    accountFund {
      code
    }
    accountFunction {
      code
    }
    accountGoal {
      code
    }
    accountLocation {
      code
    }
    accountObject {
      code
    }
    accountResource {
      code
    }
    accountYear {
      code
    }
    data
    startDate
    endDate
    updatedAt
    errors
    organizationName
    persisted
    valid
    xlsxUrl
    pdfUrl
    months
    monthTitles
    colspanWidth
  }
}
