query {
  report: budgetVsActualReport {
    data
    persisted
    valid
    errors
    startDate
    endDate
    pdfUrl
    xlsxUrl
    colspanWidth

    accountFund {
      code
    }
    accountFunction {
      code
    }
    accountGoal {
      code
    }
    accountLocation {
      code
    }
    accountObject {
      code
    }
    accountResource {
      code
    }
    accountYear {
      code
    }
  }
}
