query {
  cashFlowReport {
    valid
    errors
    reportDate
    startDate
    endDate
    fiscalYear
    organizationName

    reports {
      fund {
        name
        code
      }
      cashAtBeginning
      cashAtEnd
      financingActivities {
        name
        code
        balance
      }
      financingActivitiesTotal
      investigatingActivities {
        name
        code
        balance
      }
      investingActivities {
        name
        code
        balance
      }
      investingActivitiesTotal
      netCash
      netCashIncrease
      netIncome
      netOperationsCash
      otherIncome {
        name
        code
        balance
      }
      otherIncomeTotal
    }

    # Account Search
    accountFund {
      code
      name
    }
    accountFunction {
      code
    }
    accountGoal {
      code
    }
    accountLocation {
      code
    }
    accountObject {
      code
    }
    accountResource {
      code
    }
    accountYear {
      code
    }

    pdfUrl
    xlsxUrl
  }
}
