query {
  ap_aging_report {
    periodNames
    vendorsByPeriod
    periodsByVendor
    persisted
    valid
    errors
    startDate
    endDate
    daysPerPeriod
    showActiveColumns
    showActiveRows
    periods
    pdfUrl
    xlsxUrl
  }
}
