query vendors($aasm_state: String, $name: String, $number: String) {
  vendorSearch(aasm_state: $aasm_state, name: $name, number: $number) {
    id
    name
    fullName
    email
    aasmState
    displayName
    accountNumber
    path
    editPath
    permissions {
      index
      edit
      view
      delete
      save_draft
      send_for_approval
      reverse_approval
      approve
      deny
    }
  }
}
