export default {
  filesUploaded: [
    {
      filename: "Invoice 3.pdf",
      handle: "BdY389RbTvGncGZSoKE3",
      mimetype: "application/pdf",
      originalPath: "Invoice 3.pdf",
      size: 80158,
      source: "local_file_system",
      url: "https://cdn.filestackcontent.com/BdY389RbTvGncGZSoKE3",
      uploadId: "qs6o5k4XBnUkry0z",
      originalFile: {
        name: "Invoice 3.pdf",
        type: "application/pdf",
        size: 80158,
      },
      status: "Stored",
      key: "9otoZ17SRMCKgSq0Cok6_Invoice 3.pdf",
      container: "limeliteds",
    },
    {
      filename: "Invoice 2.pdf",
      handle: "b1D1dAtMQM2NbmSaM0FL",
      mimetype: "application/pdf",
      originalPath: "Invoice 2.pdf",
      size: 49193,
      source: "local_file_system",
      url: "https://cdn.filestackcontent.com/b1D1dAtMQM2NbmSaM0FL",
      uploadId: "XG7Swt1YHvOD4g1m",
      originalFile: {
        name: "Invoice 2.pdf",
        type: "application/pdf",
        size: 49193,
      },
      status: "Stored",
      key: "OwZUmnxWSd2CShAnGyGU_Invoice 2.pdf",
      container: "limeliteds",
    },
    {
      filename: "Invoice.pdf",
      handle: "cZDHRgmIRLqcPOd40sda",
      mimetype: "application/pdf",
      originalPath: "Invoice.pdf",
      size: 49274,
      source: "local_file_system",
      url: "https://cdn.filestackcontent.com/cZDHRgmIRLqcPOd40sda",
      uploadId: "DdKquKK6I0Y0b4yl",
      originalFile: {
        name: "Invoice.pdf",
        type: "application/pdf",
        size: 49274,
      },
      status: "Stored",
      key: "Gf7Xc7qWR2qaSTdH8aay_Invoice.pdf",
      container: "limeliteds",
    },
  ],
  filesFailed: [],
};
