# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bf03e216fac2eee38e7a1135bc870aa43ed91e946d5bd4129486d8e43eb4a502d850e3a99254c3768dd340b199fba2e7ab4406a13d0a5b10c726bfcb931a197

test:
  secret_key_base: de9a79b011f3da1eb68da33b1f42cac7bcefff7438709910931d7a99d9159e0c99129e9631cf3e9944a41d9bc897428fcda2ed199802e866a923ff0c09fecced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
